title: Recursive Awesome
description: > # this means to ignore newlines until "show_excerpts:"
  Recursive Awesome uses Machine Learning and Artifical Intelligence with mobile and cloud applications to help companies make their products smarter and create better customer experiences.
#url: https://cookie-demo.netlify.app # change this URL, this is needed for generating right sitemap
#url: https://recursiveawesome.com # change this URL, this is needed for generating right sitemap
baseurl: ""
url: "https://recursiveawesome.github.io" # change this URL, this is needed for generating right sitemap
#url: https://recursiveawesome.com # change this URL, this is needed for generating right sitemap

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-purgecss
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true

soopr:
  publish_token: "pt_2389970f7f4b85947f557f1596c01b74" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
